// Mocks generated by Mockito 5.0.4 from annotations
// in lib_search_app/test/search_book/repository/search_book_repository_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:lib_search_app/network/search_book_api_client.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: comment_references
// ignore_for_file: unnecessary_parenthesis

/// A class which mocks [SearchBookApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchBookApiClient extends _i1.Mock
    implements _i2.SearchBookApiClient {
  MockSearchBookApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> get(String? endpoint) =>
      (super.noSuchMethod(Invocation.method(#get, [endpoint]),
          returnValue: Future<String>.value('')) as _i3.Future<String>);
}
